### ISSUE TITLE
Inline formatting single file: Breaks symlink and creates a regular file instead of retaining symlink

### ISSUE THREAD

**Issue by mechanicker** [mvdan/sh#1053] opened 2024-01-28 14:45 UTC
Before run:
```
$ ls -l shfmt.test*|sed -E 's#(dkrishnamurthy)|(staff)#dev#g'
-rw-r--r-- 1 dev dev 50 Jan 28 06:43 shfmt.test
lrwxr-xr-x 1 dev dev 10 Jan 28 06:14 shfmt.test.ln -> shfmt.test
```

Note: `shfmt.test.ln` is a symlink

After running `shfmt -w shfmt.test.ln`:
```
$ ls -l shfmt.test*|sed -E 's#(dkrishnamurthy)|(staff)#dev#g'
-rw-r--r-- 1 dev dev 50 Jan 28 06:43 shfmt.test
-rwxr-xr-x 1 dev dev 47 Jan 28 06:43 shfmt.test.ln*
```

Note: `shfmt.test.ln` is a formatted regular file

**Comment by mvdan** [comment] 2024-01-28 15:40
Duplicate of https://github.com/mvdan/sh/issues/843.

**Closed by mvdan** 2024-01-28 15:40 UTC
