### ISSUE TITLE
syntax: parser errors on comments inside backquotes

### ISSUE THREAD

**Issue by SuperSandro2000** [mvdan/sh#698] opened 2021-04-29 21:42 UTC
When I try to format the following snipped with shfmt:

```bash
#!/bin/bash
cat <<EOF
`#$(echo 1)`
2
EOF
```

it errors:

```
test.sh:3:1: reached EOF without closing quote `
```

but I can execute it in bash 5.0.17(1)-release without any errors:

```
./test.sh

2
```

I am using version 3.2.4.

**Comment by mvdan** [comment] 2021-04-29 21:49
This is somewhat intentional. Bash allows parsing a comment within backticks, and the comment ends at the backtick instead of at the next newline.

Personally, I find that pretty scary. It's like the parser treats the bytes within backquotes as an entirely separate input file.

Backticks are deprecated and they shouldn't be used, so I thought it wasn't worth the effort to try to fix this rare edge case. But maybe it's time to rethink that if people are actually running into this.

**Comment by SuperSandro2000** [comment] 2021-04-29 21:54
> Bash allows parsing a comment within backticks, and the comment ends at the backtick instead of at the next newline.

I am (ab)using this behavior to quickly change generated content in a config file. When I want to deactivate a part I am putting a function in `#$()`.

```bash
`#$(gen a)` `#$(gen b)` $(gen c) `#$(gen d)` $(gen e)
```

**Comment by mvdan** [comment] 2021-05-03 17:29
How about:

```
$(enabled) $(: $(disabled))
```

Perhaps more verbose, but backquotes are deprecated, so you should really not use them.

**Comment by SuperSandro2000** [comment] 2021-05-04 11:37
That wouldn't highlight the content as comment which is the main reason I do it like this.

**Comment by mvdan** [comment] 2021-09-15 08:31
Actually, I had not noticed but this is a dupe of https://github.com/mvdan/sh/issues/698 :)

**Closed by mvdan** 2021-09-15 08:31 UTC

**Comment by SuperSandro2000** [comment] 2021-09-15 08:33
This is issue #698.

**Comment by mvdan** [comment] 2021-09-15 08:41
Sorry, copy-paste mistake. I meant https://github.com/mvdan/sh/issues/636.
