### ISSUE TITLE
interp: calling a program with >> on Windows does not append

### ISSUE THREAD

**Issue by antylama** [mvdan/sh#289] opened 2018-09-07 09:16 UTC
For simple echo it's working, but:

```sh
$ ls >> out
ls: write error: Bad file descriptor
```

ls is from Windows Git (C:\Program Files\Git\usr\bin\ls.exe).

Replace in interp\module.go, fix it, but it's bad implementation:

```golang
var DefaultOpen = ModuleOpen(func(ctx context.Context, path string, flag int, perm os.FileMode) (io.ReadWriteCloser, error) {
	if flag&os.O_APPEND != 0 {
		flag = flag & (^os.O_APPEND)
		f, err := os.OpenFile(path, flag, perm)
		f.Seek(0, 2)
		return f, err
	}
	return os.OpenFile(path, flag, perm)
})
```

**Comment by mvdan** [comment] 2018-09-07 09:57
Thanks for filing all these issues - I'm currently at the end of a short vacation, so I may be a bit slow to work through them. Out of curiosity; what are you using these packages for?

I don't have a Windows machine to test things with, so I'll have to rely on AppVeyor to debug these. If you can help debug what's going on or even submit fixes, that would be very helpful.

**Comment by antylama** [comment] 2018-09-07 12:30
I'm trying (last night) to use Your project as part of build tools in our cross platform (OSX, Windows, GNU/Linux), mainly golang project (cgo, spidermonkey). Some part's of project are in JS, C, and C++, and few tools in bash/python/cmd.

We are using traditional Makefile's (no autoconf etc., only gmake), it's generally OK, but installing correct working version of programs like bash.exe is little frustrating (gmake use sh/bash internally).

My idea is use more tools written in golang, as build tools (we try porting to Meson, but I want more control on what's going on;-)). Your `gosh`, works pretty good in OSX/Linux on our main Makefile!

**Comment by mvdan** [comment] 2018-09-07 13:36
I see - thanks for the info!

I've noticed that my code was a bit buggy, so I've pushed a commit. Please check if it happens to fix your issue. Both the old code and new work just fine on Linux.

I've also added a `wc >> file` test, so if it's still broken, I'd expect AppVeyor to fail on a master build soon.

**Comment by mvdan** [comment] 2018-09-07 13:41
Yep, there we go: https://ci.appveyor.com/project/mvdan/sh/build/303

I'll investigate further this evening.

**Comment by antylama** [comment] 2018-09-07 15:32
Strange, redirect 32bit `ls.exe >> out` from `scoop install gow` work's fine:

```cmd
C:\Users\marcin\go\src\mvdan.cc\sh\cmd\gosh>file C:\\Users\\marcin\\scoop\\apps\\gow\\current\\bin\\ls.exe
C:\\Users\\marcin\\scoop\\apps\\gow\\current\\bin\\ls.exe: PE32 executable (console) Intel 80386 (stripped to external PDB), for MS Windows
```

64bit ls.exe from Git not:

```cmd
C:\Users\marcin\go\src\mvdan.cc\sh\cmd\gosh>file "C:\Program Files\Git\usr\bin\ls.exe"
C:\Program Files\Git\usr\bin\ls.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

Gosh.exe is 64bit version.

I'm using Windows Server 2012.
For older ones: `https://support.microsoft.com/en-us/help/971163/the-stdin-the-stdout-and-the-stderr-redirections-do-not-work-in-a-wow6`

Still only reset `os.O_APPEND` flag and `Seek` to end working always.

**Comment by mvdan** [comment] 2018-09-12 11:45
I've tried a multitude of things via AppVeyor and I can't seem to find a bug in my code, so I've opened an issue on Go itself. Hopefully other Go developers that use Windows can shed some light into this.

**Comment by mvdan** [comment] 2018-09-14 08:48
@antylama could you please check if this also happens on programs not written in Go? For example, this tiny program in C works fine on Linux too:

```
$ cat caller.c
#include <unistd.h>
#include <fcntl.h>

int main() {
        if (fork() == 0) {
                int fd = open("f", O_WRONLY|O_APPEND);
                dup2(fd, 1);
                close(fd);

                char *args[] = {"echo", "bar", NULL};
                int res = execvp("echo", args);
        }
}
$ echo foo >f && gcc -o caller caller.c && ./caller && cat f
foo
bar
```

I tried my best to make that C program compile on AppVeyor with VS2017, but I completely failed after twenty minutes. I started reading up on Cygwin, but this is getting very far out of my skillset.

Really, it would be useful to see if *any* other language reproduces the same bug - be it Python, C++, Rust, or whichever you like. If any of them have it, then the problem likely lies somewhere in the Windows/Git stack, and not in Go.

**Comment by mvdan** [comment] 2018-09-14 14:28
I imagine that a `fork` is needed to reproduce this issue, yes. Although so far I've failed to get process forking to work on Windows.

The closest working program in C on Windows that I've gotten to work is:

```
#include <io.h>
#include <fcntl.h>
#include <stdio.h>

int main() {
       int fd = _open("f", _O_WRONLY|_O_APPEND);
       _dup2(fd, 1);
       _close(fd);

       char *args[] = {"echo", "bar", NULL};
       int res = _execvp("echo", args);
       printf("%d\n", res);
}
```

But like you say, this *overrides* the content, doesn't append to it. That is, if the file had `fooooo\n` in it, now it will have `bar\noo\n`. I compiled that with VS2017's clang on AppVeyor.

I also tried the following program on Python, which *also* works fine on Linux, but *also* overwrites the file contents on plain Windows with VS2017:

```
import subprocess

with open("f", "a") as f:
    p = subprocess.Popen(['echo', 'bar'], stdout=f)
    p.wait()
```

So, really, I have no idea what's going on here. Maybe MinGW/MSYS2 always require the `seek` system call following the `open`?

It would be great if you could try adding process forking to my C example, to see how it behaves then. The `open` should happen in the parent process, because that's what happens in Go too. There, we do `os.OpenFile`, and it's `exec.Cmd.Run()` which actually does the `fork` and `exec` syscalls.

**Comment by antylama** [comment] 2018-09-14 14:35
My windows Python work's fine (append, and create file if not exists) with your code.

**Comment by mvdan** [comment] 2018-09-14 14:49
I used AppVeyor's default Python, which I believe was 2.7. You can see the full details at https://www.appveyor.com/docs/build-environment/.

And of course, you can also test there. But running each job takes a minute, so it does slow my debugging compared to Linux.

**Comment by antylama** [comment] 2018-09-14 15:30
I tested for new thread, not process (It's little tricky emulate fork in Windows):

```c
#include <unistd.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>

void *thread_command()
{
    int fd = open("f", O_RDWR | O_APPEND);
    dup2(fd, 1);
    close(fd);

    char *args[] = {"echo", "bar", NULL};
    int res = execvp("echo", args);
    fprintf(stderr, "Ret: %d", res);
    return NULL;
}

int main() {
    pthread_t thread;
    pthread_create(&thread, NULL, &thread_command, NULL);
    pthread_join(thread, NULL);
    return 0;
}
```

Work's the same like before (don't append).

For example `f`:

```
bar1234
end
```

replace to:

```
bar
234
end
```

**Comment by mvdan** [comment] 2018-09-14 15:35
Thanks!

Honestly, I'm out of ideas, and very confused by all this. If at least I had a Windows machine I could continue debugging this, but I've already sunk two afternoons into it.

I think I'm going to leave both issues open for a few weeks, but I'm just going to close them if noone steps in to investigate further. The bug is clearly not in my code, as it can be reproduced by a tiny Go program. And I don't think the bug is in Go either, as other languages have encountered it - see https://github.com/msteveb/jimtcl/issues/59.

If noone finds a good solution, I'm not sure if I'll incorporate the workaround. I might just add a `ModuleOpen` variant that applies your workaround, for those users that require good support on these exotic Windows environments. I presume that most users won't want the extra complexity.

**Comment by mvdan** [comment] 2018-09-14 15:36
Another idea of something you could try. For those programs that do work with this append-fork-exec logic, such as Python3, what does `strace` say? Do they do an `open` with `O_APPEND`, or a `seek`?

**Comment by mvdan** [comment] 2018-09-14 15:41
Another drive-by comment - note that in your C example with threads, you perform the `open` in the child process/thread. To get as close as possible to how Go works, you should open the file in the parent process.

**Comment by antylama** [comment] 2018-09-14 15:43
Better code (not exiting before print `ret`), but work's the same:

```c
#include <unistd.h>
#include <fcntl.h>
#include <pthread.h>
#include <stdio.h>

void *thread_command()
{
    fprintf(stderr, "start...\n");
    int fd = open("f", O_RDWR | O_APPEND);
    dup2(fd, 1);
    close(fd);

    const char *args[] = {"echo", "bar", NULL};
    int res = _spawnvp(_P_WAIT, "echo", args);
    fprintf(stderr, "Ret: %d\n", res);

    return NULL;
}

int main() {
    pthread_t thread;
    pthread_create(&thread, NULL, &thread_command, NULL);
    pthread_join(thread, NULL);
    return 0;
}
```

**Comment by antylama** [comment] 2018-09-14 17:07
> Another idea of something you could try. For those programs that do work with this append-fork-exec logic, such as Python3, what does strace say? Do they do an open with O_APPEND, or a seek?

Unfortunately, strace talk too much, but don't say any `O_APPEND` or `seek` in both cases (working version of Python, and don't working C example).

If you write something to stdout, before `_spawnvp` then it's _works_, but it's worst then seek...

**Comment by antylama** [comment] 2018-09-14 17:31
Nothing change for this:

```c
#include <unistd.h>
#include <fcntl.h>
#include <stdio.h>
#include <windows.h>

int execute_command(const char *command, char in_console)
{
    STARTUPINFO StartInfo;
    PROCESS_INFORMATION ProcInfo;
    memset(&ProcInfo, 0, sizeof(ProcInfo));
    memset(&StartInfo, 0, sizeof(StartInfo));
    StartInfo.cb = sizeof(StartInfo);

    if (!in_console) {
        StartInfo.dwFlags = STARTF_USESHOWWINDOW;
        StartInfo.wShowWindow = SW_HIDE;
    }
    char cmd[MAX_PATH];
    sprintf(cmd, "%s -", command);
    int res = CreateProcess(NULL, (CHAR *) &cmd, NULL, NULL, 0, 0, NULL, NULL, &StartInfo, &ProcInfo);

    if (res) {
        CloseHandle(ProcInfo.hThread);
        WaitForSingleObject(ProcInfo.hProcess, INFINITE);
        DWORD exitCode = 0;
        if (GetExitCodeProcess(ProcInfo.hProcess, &exitCode)) {
            return (exitCode > 0 ? 1 : 0);
        }
        return 1;
    }
    CloseHandle(ProcInfo.hProcess);
    return res;
}

int command()
{
    const char *args[] = {"echo", "bar", NULL};
    int res = _spawnvp(_P_WAIT, "echo", args);
    fprintf(stderr, "Ret: %d\n", res);
    return res;
}

int main(int argc, char **argv) {
    if (argc == 1) {
        fprintf(stderr, "start 1\n");
        int fd = open("f", O_RDWR | O_CREAT | O_APPEND );
        dup2(fd, 1);
        close(fd);
        execute_command(argv[0], 1);
    } else {
        fprintf(stderr, "start 2\n");
        command();
    }
    return 0;
}
```

**Comment by antylama** [comment] 2018-09-17 14:50
I found something, when start gash from `cmd.exe` (`echo` from Git):

```cmd
gosh -c "echo bar >> out"
echo: write error: Bad file descriptor
exit status 1
```

but, when you give `echo` a chance, and run the same from `bash` (from Git):

```cmd
C:\> bash
$ gosh -c "echo bar >> out"
```

it works!

Bash from Git, emulate some UNIX devices, like `/dev/fd/0`:

```cmd
ls /dev
clipboard  conout  console  fd    kmsg    null  random  sda   sda2  sdb1  shm  stderr  stdout  ttyS2  urandom  zero
conin      cons0   dsp      full  mqueue  ptmx  scd0    sda1  sdb   sdb2  sr0  stdin   tty     ttyS4  windows
```

(above `ls` is from Git, so it's works in cmd.exe too). Maybe `gosh` should do some magic ;-).

**Comment by mvdan** [comment] 2018-09-17 18:12
Sorry, but I'd like to keep the Windows magic at a minimum. The interpreter already does a bit of magic to support common idioms natively, such as `/dev/null`, but I won't extend that much further. The "linux/bash on windows" can do fancier stuff since it can implement system calls and other low-leve linterfaces, but we simply can't as a higher-level shell interpreter.

I guess it makes sense that starting `gosh` under this weird Linux/POSIX emulation mode makes the open/exec combo work. Since then, the file descriptor passed between processes originates and is used by the same mingw/cygwin system. In our original example, it's a plain old Windows virtual file descriptor that is passed to mingw.

**Comment by mvdan** [comment] 2018-12-02 16:50
It's been over a month; closing as per the comment above.

**Closed by mvdan** 2018-12-02 16:50 UTC
Labels: help wanted, needs info
