### ISSUE TITLE
v3.2.0 memory leak?

### ISSUE THREAD

**Issue by slintes** [mvdan/sh#625] opened 2020-11-02 09:35 UTC
Hi,

we use `shfmt` at https://github.com/kubevirt/node-maintenance-operator. We fail to run the latest version v3.2.0 on our dev machines and on CI (Travis), it is running out of memory.

Reproducable by cloning above repo and running `make check`

Workaround: pin to version 3.1.2 in go.mod:

```
replace (
	mvdan.cc/sh/v3 => mvdan.cc/sh/v3 v3.1.2
)
```

**Comment by mvdan** [comment] 2020-11-02 10:04
Thank you for the report! This appears to be the same issue as https://github.com/mvdan/sh/issues/626, caused by this line:

```
$ git grep -n '\$\{[^}]*/[^}]*'"'"
hack/sync-deploy.sh:7:    export FULL_INDEX_IMAGE="${IMAGE_FORMAT//'${component}'/node-maintenance-operator-index}"
```

I'll have a fix for that issue shortly, and I've verified it also fixes `shfmt -l -w .` on your repository. I'm closing this as a duplicate - your issue is slightly older, but I looked at the other one first since it had a specific shell line I could look into :)

**Closed by mvdan** 2020-11-02 10:04 UTC

**Comment by slintes** [comment] 2020-11-02 10:44
Thanks for the quick respone :+1: :slightly_smiling_face:
