### ISSUE TITLE
Exclude formatting for code between `# @formatter:off` and `# @formatter:on`

### ISSUE THREAD

**Issue by AlexSkrypnyk** [mvdan/sh#1030] opened 2023-09-07 10:46 UTC
Can we please have a new feature to exclude code formatting for lines between `# @formatter:off` and `# @formatter:on`

**Comment by mvdan** [comment] 2023-09-07 11:01
Duplicate of https://github.com/mvdan/sh/issues/963, https://github.com/mvdan/sh/issues/933, https://github.com/mvdan/sh/issues/700.

If there is a bug, please file a bug. Otherwise, the tool isn't meant to be used for chunks of code. You can always split your scripts into multiple files, and choose to only format some of them.

**Closed by mvdan** 2023-09-07 11:01 UTC
