### ISSUE TITLE
syntax: multiple runs with BinaryNextLine cause extra newlines

### ISSUE THREAD

**Issue by PanovEduard** [mvdan/sh#158] opened 2017-09-04 12:56 UTC
for example: you have [ ... ] && {...}
after first run with -bn you'll get 
[ ... ] \
  && {
    ...
  }
after second:
[ ... ] \
  \
  && {
    ...
  }
and so on...

**Comment by mvdan** [comment] 2017-09-04 13:50
I cannot reproduce this on master. Could you give a small script that would reproduce this issue?

**Comment by PanovEduard** [comment] 2017-09-04 14:49
[ $PREPARE_MAIL -eq 1 ] \
\
\
\
  && {
    MAIL_BODY=$(NewTmpFile "$SCRIPT_DIR/log/mailbody.tmp") || ErrorHandling -m "($SCRIPT_NAMEline:$LINENO) Файл \"mailbody.tmp\"невозможно удалить. Функция NewTmpFile: "-cs
    MAIL_LOG=$(NewTmpFile "$SCRIPT_DIR/log/log.txt") || ErrorHandling -m "($SCRIPT_NAME line:$LINENO) Файл \"log.txt\"невозможно удалить. Функция NewTmpFile: "-cs
  }
 
This is fourth iterations result, by the way it's reproducing now even without -bn key.
Shfmt Ver – 2.0 build for win 386
This happens when I using vs code plugin , may be I'm wrong , and bug is in this plugin?
Plugin config string is:
"shellformat.flag": "-i 2 -ci -bn -ln bash -s",
 

--
Отправлено из Mail.Ru для Android понедельник, 04 сентября 2017г., 16:50 +03:00 от Daniel Martí  notifications@github.com :

**Comment by mvdan** [comment] 2017-09-04 14:55
That still doesn't reproduce the issue. If you paste those lines into a file and run `shfmt` on them, it formats correctly.

The cause of the issue is likely a previous part of the script - could you link or paste the entire thing? If you can't, then you should try to get a smaller version that you can share that would still reproduce the issue.

**Comment by PanovEduard** [comment] 2017-09-04 15:06
the whole script is about 2800 lines, but i reproduce it exactly on this part, and even without -bn? but  only in case when you use \ to split lines
[] \
&& {
... 
}

**Comment by mvdan** [comment] 2017-09-04 15:31
To reiterate; I can't fix an issue I cannot reproduce. I understand what you're trying to say, but without a complete shell script that will let me see this issue, I cannot debug it and fix it.

If you want to see if a script shows the issue or not, you can run `shfmt` through it yourself, or you can use the VS plugin on that file.

**Comment by PanovEduard** [comment] 2017-09-05 08:56
I've tryed to reproduce this behaviour without vs plugin - unsuccessfully, so the problem is in plugin. Sorry for false alarm.

**Comment by mvdan** [comment] 2017-09-06 10:27
I would imagine the bug is still with `shfmt`, not the plugin, as I fixed a similar bug a while back. And it would be very strange for the plugin to be the cause of such a specific issue.

I'll leave this issue open for now, in case you can give me more information that will help me reproduce and debug it.

**Comment by mvdan** [comment] 2017-09-22 17:57
As there's still not enough information for me to reproduce, I'm going to close this for now.

**Closed by mvdan** 2017-09-22 17:57 UTC
Labels: needs info
