### ISSUE TITLE
Is there possible to break down multiple arguments to lines, one parameter per one line,thanks

### ISSUE THREAD

**Issue by godhelpjun** [mvdan/sh#731] opened 2021-09-17 14:53 UTC
example
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true 

to lines like this
  /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 \
    -Des.networkaddress.cache.negative.ttl=10 \
    -XX:+AlwaysPreTouch \
    -Xss1m -Djava.awt.headless=true

**Comment by mvdan** [comment] 2021-09-17 14:58
Have you seen https://github.com/mvdan/sh/issues/80?

**Comment by mvdan** [comment] 2021-09-26 10:25
I'm going to assume that this is a duplicate of #80.

**Closed by mvdan** 2021-09-26 10:25 UTC
Labels: needs info
