### ISSUE TITLE
shfmt considers export {foo,bar}= as an invalid variable

### ISSUE THREAD

**Issue by mikeBashStuff** [mvdan/sh#980] opened 2023-03-16 12:34 UTC
The following example is a valid Bash code:

```
export {FOO,BAR}=
export {foo,bar}=this_is_valid

declare -p {FOO,BAR,foo,bar}

$ ./foo
declare -x FOO=""
declare -x BAR=""
declare -x foo="this_is_valid"
declare -x bar="this_is_valid"
```

However, `shfmt` (checked the latest v3.6.0 release as well) reports a following error:
```
# SHFMT_NO_EDITORCONFIG=true shfmt-3.6.0 -i 0 -bn -ci -ln bash -d -sr ./foo
./foo:1:8: invalid var name
#
```

**Comment by mvdan** [comment] 2023-03-16 21:03
See https://github.com/mvdan/sh/issues/858#issuecomment-1155078373 and the last example under https://github.com/mvdan/sh#caveats. This is a known limitation. Closing as a duplicate of 858, because both are different examples of the same problem.

**Closed by mvdan** 2023-03-16 21:03 UTC
