### ISSUE TITLE
echo "${.sh.version}" breaks shfmt

### ISSUE THREAD

**Issue by mcandre** [mvdan/sh#511] opened 2020-02-18 22:47 UTC
When I try to format my korn shell scripts with shfmt, then this line triggers an error.

```ksh
echo "${.sh.version}"
```

```console
$ shfmt -w -i 4 version 
version.sh:3:9: invalid parameter name
```

Please don't present errors for valid ksh string interpolation syntax.

**Comment by mvdan** [comment] 2020-02-19 08:38
We support POSIX Shell, Bash, and mksh. As far as I know, that's not valid syntax in any of them.

You already raised an issue about ksh support in https://github.com/mvdan/sh/issues/161, but I got no answer, just like with multiple other of your issues. I'm not going to work on ksh support unless there's a good reason for it, so I'm closing this for now. Feel free to reply later and I might re-open.

**Closed by mvdan** 2020-02-19 08:38 UTC

**Comment by willemml** [comment] 2023-09-25 04:46
I have found an edge case where this is valid bash code but shfmt detects it as an error.

```bash
$ TEST=test '${.sh.version}'
bash: ${.sh.version}: command not found

$ echo '${hello.there}'
${hello.there}
```

My use case is editing bash code blocks in a nix config file, these can have nix variable substitution which uses that syntax. The use case is irrelevant to the "bug" though because this error is given even if the "invalid parameter name" is commented out. I do not use ksh but this not being detected as an error would be helpful for strings and comments that contain similarly formatted text.

**Comment by mvdan** [comment] 2023-10-25 08:14
@willemml that seems to work for me; in single quotes, the parameter expansions are not parsed at all.

If your example used double quotes, like in the original post, then that's still a matter of what shell syntax this is, because it doesn't appear to be Bash. Assuming it is some other shell dialect, I'd suggest that you file a new issue to request supporting it with more details, such as its documentation or spec.

The bash interpreter unfortunately is rather lazy about invalid parameter expansions - rather than failing on them, it leaves them as plain strings. Our parser is stricter than that by design, and I don't think we would want to change that.

**Comment by sizur** [comment] 2024-12-31 00:50
It is a valid POSIX way to test for validity of a variable name.  For example, the following is a POSIX compliant function executable in Bash, Zsh, and Ksh, that robustly identifies if we're in Bash or not, between the three shell types:

```bash
# `shopt` is not a Zsh builtin.
# `BASH_VERSINFO` is a readonly variable in Bash.
# `.sh.version` is an invalid variable name in Bash.
_posix_test_am_bash() {
    # shellcheck disable=SC2030,SC2031
    if [ "$(builtin type -t builtin 2>/dev/null)" = "builtin" ] \
    && [ "$(builtin type -t shopt   2>/dev/null)" = "builtin" ]  \
    && ! ( set -u; : "${.sh.version}"    ) > /dev/null 2>&1       \
    && ! (             BASH_VERSINFO=(0) ) > /dev/null 2>&1
    then
        # POSIX compliance can be dropped here.
        _posix_test_am_bash() { builtin return 0; }
        builtin return 0
    else
        # Can't guarantee the `builtin` builtin, nor `readonly -f`.
        _posix_test_am_bash() { return 1; }
        return 1
    fi
}
```

`shfmt` correctly identifies syntax errors here, but it doesn't even let you dump the syntax tree of a perfectly valid POSIX compliant function with `--to-json` due to `invalid parameter name` error.

**Comment by sizur** [comment] 2024-12-31 12:05
These work and are no problem for `shfmt` to output parse tree:
```bash
_compat_test_am_zsh() {
    # shellcheck disable=SC2034 # foo appears unused. Verify it or export it.
    if [ "x$(builtin whence -w builtin 2>/dev/null)" = "xbuiltin: builtin" ]\
    && [ "x$(builtin whence -w setopt  2>/dev/null)" = "xsetopt: builtin"  ] \
    && ! ( eval '[ -n "${.sh.version}" ]'        ) >/dev/null 2>&1            \
    && ! (    ZSH_EVAL_CONTEXT=""                ) >/dev/null 2>&1            \
    && ! ( (( ZSH_SUBSHELL=0 , ZSH_SUBSHELL++ )) ) >/dev/null 2>&1
    then
        _SHELL_TYPE="zsh"
        eval '_SHELL_VERSION="${(j:.:)${${(s:.:)ZSH_VERSION}[@]:0:2}}"' \
             || return 1
        _compat_test_am_zsh() { builtin return 0; }
        builtin return 0
    else
        _compat_test_am_zsh() { return 1; }
        return 1
    fi
}

_compat_test_am_bash() {
    # shellcheck disable=SC2030,SC2031
    if [ "x$(builtin type -t builtin 2>/dev/null)" = "xbuiltin" ]\
    && [ "x$(builtin type -t shopt   2>/dev/null)" = "xbuiltin" ] \
    && ! ( eval '[ -n "${.sh.version}" ]' ) >/dev/null 2>&1        \
    && ! (              BASH_VERSINFO=(0) ) >/dev/null 2>&1
    then
        _SHELL_TYPE="bash"
        eval '_SHELL_VERSION="${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]}"' \
             || return 1
        _compat_test_am_bash() { builtin return 0; }
        builtin return 0
    else
        _compat_test_am_bash() { return 1; }
        return 1
    fi
}

# `shopt` and `setopt` are not Ksh builtins.
# `.sh.version` is an illegal veriable name in Bash and Zsh.
_compat_test_am_ksh() {
    if   [ "x$(whence -t whence 2>/dev/null)" = "xbuiltin" ]\
    && ! [ "x$(whence -t shopt  2>/dev/null)" = "xbuiltin" ] \
    && ! [ "x$(whence -t setopt 2>/dev/null)" = "xbuiltin" ]  \
    &&   (           ZSH_EVAL_CONTEXT=""  ) >/dev/null 2>&1    \
    &&   (              BASH_VERSINFO=(0) ) >/dev/null 2>&1     \
    &&   ( eval '[ -n "${.sh.version}" ]' ) >/dev/null 2>&1
    then
        _SHELL_TYPE="ksh"
        # Test for some ksh93 features
        # TODO: check if `.sh.version` is already excluding older Ksh
        if (              [ "$((sqrt(9)))" = "3" ] ) 2>/dev/null \
        && ( v=( x="X" y="Y" ); [ "${v.y}" = "Y" ] ) 2>/dev/null
        then
            _SHELL_VERSION="93.0"
        else
            _SHELL_VERSION="0.0"
        fi
        _compat_test_am_ksh() { return 0; }
        return 0
    else
        _compat_test_am_ksh() { return 1; }
        return 1
    fi
}
```
