### ISSUE TITLE
shfmt throws errors on variable declaration with brace expansion

### ISSUE THREAD

**Issue by Popkornium18** [mvdan/sh#986] opened 2023-03-21 08:30 UTC
A convenient way to set a lot of variables to the same value is this:

```
declare -i VAR_{1..4}=0
echo ${VAR_1@A} ${VAR_2@A}
"declare -i VAR_1='0' declare -i VAR_2='0'"
```

However, when shfmt encounters such a statement it prints: "invalid var name".

**Comment by mvdan** [comment] 2023-03-21 15:07
Duplicate of https://github.com/mvdan/sh/issues/858.

**Closed by mvdan** 2023-03-21 15:07 UTC
