### ISSUE TITLE
Despite -bn, line following the break is still indented 

### ISSUE THREAD

**Issue by mikeBashStuff** [mvdan/sh#529] opened 2020-03-26 10:26 UTC
Example:
```
--- ./t.orig
+++ ./t
@@ -1,7 +1,7 @@
 #!/bin/bash

 if [[ -v foo ]] \
-&& [[ -v bar ]]; then
+       && [[ -v bar ]]; then
        echo "$foo-$bar"
 fi
```
In here, `shfmt` was run with the `-bn` and `-i 0` args. Now, I guess that the break at the very top tells `shfmt` to indent the line that follows `\`, but those are part of the same single logic expression and 
 `shfmt` was explicitly told that logic operators can start a line. Additionally, as a result, the line below gets aligned with the part of the `if` expression.  It compares in my mind to having something like this basically:

```
if :; then
foo
fi
```

I don't say this is a bug or anything, more as a conscious formatting choice, however, I would appreciate some feedback on if it's possible for you to easily make `shfmt` handle scenarios like that without actually applying the indentation. :)

**Comment by mvdan** [comment] 2020-03-30 09:40
Hm - I think this is working as intended. "can start a line" doesn't imply excluding indentation. Backslashes introduce a level of indentation, just like opening a block:

```
foo \
    bar
```

> Additionally, as a result, the line below gets aligned with the part of the `if` expression.

Yeah, that's the tradeoff we make. The alternative would be to support "stacked indentation", like:

```
if [[ -v foo ]] \
        && [[ -v bar ]]; then
    echo "$foo-$bar"
fi
```

However, this can get crazy pretty fast. The indentation level could increase by three or four levels in a single line. Instead, what we do is follow what I think is an OK tradeoff made by `gofmt` - each line can only increase the indentation level by one.

It does lead to some perhaps confusing edge cases, though. Like you say above, some lines appear to belong to the same level/block, when they don't. For example, in Go:

```
func foo(first int,
    second int) {
    println(first, second)
}
```

Note how the second argument is at the same level as the body. I personally avoid this ugly edge case by avoiding newlines in function declarations or if statement conditions, and if I really must use many lines, I leave an empty line later to clarify the separation:

```
func foo(first int,
    second int) {

    println(first, second)
}
```

Following the same principle, this isn't super pretty, but I think it's okay for very long conditions:

```
if [[ -v foo ]] \
    && [[ -v bar ]]; then

    echo "$foo-$bar"
fi
```

**Comment by mvdan** [comment] 2020-03-30 09:56
That was a bit long, but it was necessary to give some context :)

I'm open to ideas on how we could do this better in the future. But we can't change this rule in v3 right now, because that would be a breaking change.

**Comment by mikeBashStuff** [comment] 2020-03-30 11:09
Appreciate your input, thanks! 

>but I think it's okay for very long conditions

Yes, I can stand behind that argument too, it actually aligns quite nicely when I think of it.

Again, thanks for explaining the rationale behind things. With this knowledge I am perfectly fine with `shfmt`'s behavior in this particular case. It's definitely something to get used to, but I can't really argue with the logic behind this choice. :)

**Comment by mvdan** [comment] 2020-03-30 11:13
Thanks for your feedback! I definitely agree it takes some using to, but I can't think of a clearly better approach without ugly side effects. The only other possible tradeoff would be to *never* indent backslash continuations, but then we'd make some common use cases pretty ugly:

```
if foo; then
    for bar in $(...); do
        long-command \
$foo $bar
    done
fi
```

I'm closing this for now, but we can resurrect this thread in the future if anyone has any suggestion.

**Closed by mvdan** 2020-03-30 11:13 UTC
