### ISSUE TITLE
illegal character U+0023 '#'

### ISSUE THREAD

**Issue by yjbdsky** [mvdan/sh#461] opened 2019-12-24 05:48 UTC
xx.sh:1:1: illegal character U+0023 '#'

`#!/bin/bash`

**Comment by mvdan** [comment] 2019-12-24 05:51
Can you provide the full file that's causing this issue, and what shfmt version you are on? I can't reproduce the issue on master with the input you provided.

**Comment by mvdan** [comment] 2019-12-30 12:11
Got no answer; closing for now.

**Closed by mvdan** 2019-12-30 12:11 UTC
Labels: needs info
