### ISSUE TITLE
Ugly format with continous line character when using assoc array with pipe symbol in subscript

### ISSUE THREAD

**Issue by d630** [mvdan/sh#533] opened 2020-04-03 05:41 UTC
v3.0.2

```bash
shfmt <<IN
#!/usr/bin/env bash

declare -A foo

foo=(
        ['|']='a x'

        ['|a|']='b c'
        ['|a|b']=
        ['|a|c|']='1 2 3'
        ['|a|c|1']=
        ['|a|c|2']=
        ['|a|c|3']=

        ['|x|']='y z'
        ['|x|y']=
        ['|x|z']=
)
IN
```

Output:

```bash
#!/usr/bin/env bash

declare -A foo

foo=(
    ['|']='a x'
    [\
    '|a|']='b c'
    ['|a|b']=
    ['|a|c|']='1 2 3'
    ['|a|c|1']=
    ['|a|c|2']=
    ['|a|c|3']=
    [\
    '|x|']='y z'
    ['|x|y']=
    ['|x|z']=
)
```

**Comment by mvdan** [comment] 2020-04-03 10:39
Thanks, this does look like a bug.

**Comment by mvdan** [comment] 2020-04-03 10:40
Ah - this is already fixed in master, and a duplicate of https://github.com/mvdan/sh/issues/521. Version 3.1.0 will be released shortly, as soon as I figure out some weird errors with docker buildx :)

**Closed** 2020-04-03 10:40 UTC

**Comment by d630** [comment] 2020-04-03 13:27
great
