### ISSUE TITLE
"for foo [in words]" must be followed by "do"

### ISSUE THREAD

**Issue by ishandutta2007** [mvdan/sh#452] opened 2019-11-26 11:27 UTC
> get_counts_by_spider.sh:21:5: "for foo [in words]" must be followed by "do"

Line 21 is actually just beginning of a for loop like this:

`    for((i=0;i<${#files[*]};++i)){
`

**Comment by mvdan** [comment] 2019-11-26 11:29
Duplicate of #444.

**Closed by mvdan** 2019-11-26 11:29 UTC
