### ISSUE TITLE
syntax: KeepPadding is unstable when reindenting a file

### ISSUE THREAD

**Issue by cornfeedhobo** [mvdan/sh#652] opened 2021-01-01 15:38 UTC
shfmt rewrites

```bash
if true ; then
  echo 'foobar'
fi
```

to

```bash
if true; then
  echo 'foobar'
fi
```

1) Why is this space being removed?
1) Is there an official formatting doc that says multi-statement lines should be minified as much as possible?
1) Can this be configured?

**Comment by mvdan** [comment] 2021-01-01 15:56
1 - the formatter tries to use a canonical format that's closest to what most people use. Many of its choices are arbitrary, and would require breaking changes to be reversed.

2 - I don't understand what you mean. This is formatting, not minifying. shfmt has a minify flag which is entirely different.

3 - shfmt has a bunch of flags you can look at, but none of them should affect this particular decision.

**Comment by cornfeedhobo** [comment] 2021-01-01 16:36
1) okay
1) I just couldn't think of a better word for why that space would be removed.
1) okay

**Comment by cornfeedhobo** [comment] 2021-01-02 22:03
@mvdan I'm playing around more, and after noticing that `shfmt` doesn't correct this:

```bash
set    -e
```
to
```bash
set -e
```
I'm still left wondering why the space after an if condition and before the semi-colon has to be removed.

I really appreciate the candid comment that it's arbitrary, but given that it's not consistent, couldn't this rule be silently dropped and not affect anyone?

**Comment by mvdan** [comment] 2021-01-08 14:51
> Edit: This actually is fixed if `shfmt` is invoked twice, so I think I found a bug.

Yeah, shfmt not being "stable" after one run is a bug. Can you provide a reproducer?

**Comment by cornfeedhobo** [comment] 2021-01-08 15:12
@mvdan No problem, [here's a gist](https://gist.github.com/cornfeedhobo/79c0c69f16e4503250c3b36191a6d30b) of a working example. It's actually a fun one because you have to run shfmt 6 times to get the final correct state, and it actually is adding the whitespace it's removing in the subsequent runs. Config is also included.

**Comment by mvdan** [comment] 2021-01-08 15:31
Hm, I cannot reproduce:

```
$ curl -s https://gist.githubusercontent.com/cornfeedhobo/79c0c69f16e4503250c3b36191a6d30b/raw/34b5934405bc0d55c519c16f27659792d0854d2a/helper-snippet.bash >f.bash
$ shfmt -w f.bash
$ shfmt -d f.bash
$ shfmt -version
v3.2.1-0.20201210150800-b944d9800970
```

This is formatting the file once (with -w and the default options), and then checking that a second format would result in an empty diff.

**Comment by cornfeedhobo** [comment] 2021-01-08 15:59
@mvdan you'll need to set your flags to match the included editorconfig settings in that gist.

**Comment by mvdan** [comment] 2021-01-08 16:01
Oh, I hadn't noticed the options, thanks.

**Comment by mvdan** [comment] 2021-01-20 22:41
The "keep padding" flag is to blame here. I really wish I hadn't written this feature, because it's riddled with edge cases that behave in bad ways. See https://github.com/mvdan/sh/issues/362, for example.

How badly do you want to use that flag? If you disable it, the file formats nicely in a single pass and it's stable from then on.

I might still fix this bug, but I'm seriously considering whether it's worth it to invest many more hours into that feature that, as far as I know few people use.

**Comment by cornfeedhobo** [comment] 2021-01-25 01:50
@mvdan We've dropped it's usage. I don't have any strong feelings about this, so I support you killing it if it adds too much complexity for now.

**Comment by mvdan** [comment] 2021-01-25 12:56
Thanks @cornfeedhobo. Your experience with bash-it gave me enough confidence to finally put the killing of `-kp` into words :) See https://github.com/mvdan/sh/issues/658.

**Comment by mvdan** [comment] 2022-10-23 13:37
KeepPadding will definitely be removed in the future v4; see https://github.com/mvdan/sh/issues/658. Closing all existing bug reports as I won't focus more effort on attempting to fix the feature. I'd definitely recommend not to use the option anymore :)

**Closed by mvdan** 2022-10-23 13:37 UTC
