### ISSUE TITLE
expand: glob errors on trying to readdir files instead of skipping them

### ISSUE THREAD

**Issue by antonmarin** [mvdan/sh#347] opened 2019-01-09 09:57 UTC
Broken expression `docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0 --color=always --shell=bash --exclude=SC2181 build/docker/*/*.sh` inside `go-task/task` while fixing #336

Taskfile:
```
  lint-shell:
    cmds:
      - docker run -tv "$PWD:/mnt" koalaman/shellcheck:v0.5.0
        --color=always --shell=bash --exclude=SC2181
        build/docker/*/*.sh
```

Same with `**/*.sh`

**Comment by mvdan** [comment] 2019-01-11 11:37
Sorry, I don't understand this issue. Please give a short shell program that works on sh or bash and fails in gosh (see https://github.com/mvdan/sh#gosh).

**Comment by antonmarin** [comment] 2019-01-11 11:39
May i use go-task/task for this ?

**Comment by mvdan** [comment] 2019-01-11 11:41
You can, but I don't know task at all, so it's going to make my life harder. In the end, I'll only fix bugs that I can reproduce with a bit of effort.

task uses the same interpreter that `gosh` uses, so I expect it would be simple to reproduce the same globbing bug.

**Comment by antonmarin** [comment] 2019-01-11 12:12
[gosh-347.zip](https://github.com/mvdan/sh/files/2749531/gosh-347.zip)

Use `./run_this.sh`

**Comment by mvdan** [comment] 2019-01-11 12:17
Thanks. I can reproduce the issue, and I can see the cause.

```
$ bash -c 'echo build/docker/*/*.sh'
build/docker/test/test.sh
$ gosh -c 'echo build/docker/*/*.sh'
readdirent: not a directory
```

The issue is that we should be skipping `build/docker/docker-compose.yaml` in that glob since it's not a directory, but instead we're erroring. `master.v3` gets this right, but `master` fails. I'll need to backport a small fix into 2.6.3.

**Comment by antonmarin** [comment] 2019-01-11 12:18
Thanks a lot

**Comment by mvdan** [comment] 2019-01-11 12:21
Also, I just checked, and this issue affects 2.6.0 and 2.6.1 too. So it's not a recent regression.

**Comment by mvdan** [comment] 2019-01-15 22:52
This is the third glob bug fixed in master since the last stable release last month, so I'll likely tag 2.6.3 tomorrow.

**Closed** 2019-01-15 22:51 UTC
Labels: bug
