### ISSUE TITLE
Add Dockerfile format

### ISSUE THREAD

**Issue by sbrunner** [mvdan/sh#640] opened 2020-12-06 09:13 UTC
Some plugin using this project like:
- https://marketplace.visualstudio.com/items?itemName=foxundermoon.shell-format
- https://github.com/rx-ts/prettier/tree/master/packages/sh

Use this formatter to format Dockerfile and with correct option, the result is not so bad but in prefect...

Isn't possible to support it officially?

The issues I detect:
Removing some ending '; \':
```dockefile
RUN set -eux; \
    false; \
    true
```
=>
```dockefile
RUN set -eux
false
true
```
Error with multiline `if` and `for`:
```dockefile
RUN if [ "$TEST" == TRUE ]; \
    then \
    echo test; \
    fi
```
=> error:
```
"then" can only be used in an if
```

```dockerfile
RUN for item in "${TEST}"; \
    do \
        echo $item; \
    done
```
=> error:
```
"do" can only be used in a loop
```

**Comment by mvdan** [comment] 2020-12-07 15:02
Sorry, but this software does not aim to parse or format Dockerfiles. It parses and formats shell. Dockerfiles simply embed bits of shell in them, but the overall syntax is *not* shell.

A previous occurrence of this issue is https://github.com/mvdan/sh/issues/424. cc @JounQin @kaey 

My overall thoughts are that someone could easily build a Dockerfile formatter in Go on top of this shell formatter. The closest one that I know of is https://github.com/jessfraz/dockfmt; it does its own simple formatting of shell code, which is why I raised https://github.com/jessfraz/dockfmt/issues/2 a while back. The issue is labeled "help wanted", so I'm sure a PR would be welcome.

**Comment by JounQin** [comment] 2021-03-24 22:52
@sbrunner `binaryNextLine` is auto enabled in `prettier-plugin-sh`, so actually it's not a problem for `prettier-plugin-sh`.

**Comment by mvdan** [comment] 2021-03-25 03:16
I got no answer to the above, so closing.

**Closed by mvdan** 2021-03-25 03:16 UTC
Labels: needs info

**Comment by reteps** [comment] 2025-04-06 18:38
Hello, I have made a new dockerfile formatter with this feature. Check it out here: https://github.com/reteps/dockerfmt
