### ISSUE TITLE
cmd/shfmt: shfmt can change the interpreter by removing a leading newline

### ISSUE THREAD

**Issue by MaeIsBad** [mvdan/sh#936] opened 2022-10-24 08:39 UTC
A file like:
```

#!/usr/bin/env bash
echo $SHELL
```
will be executed in the current shell, due to the leading newline. Running shfmt on it will discard the newline, leading to the interpreter being changed to bash.

I've tested this on the latest master commit(6ba49e2c622e3f56330f4de6238a390f395db2d8)

**Comment by theclapp** [comment] 2022-10-24 13:54
For those of you reading along at home, the issue is clearer at Github.  The file in question is

```
--- start ---
\n
#!/usr/bin/env bash\n
echo $SHELL\n
--- end ---
```

@MaeIsBad I'm not @mvdan, and I'm not saying this isn't a bug.  Is this something you just happened to notice, or is this an idiom you actually use?  If the latter, I'd be interested to hear why.  It seems like it'd be rife for bugs or at least confusion.

**Comment by mvdan** [comment] 2022-10-24 14:02
Yeah, I'm a bit puzzled by this idiom as well. Many editors will complain or remove trailing empty lines in a file, for example, so I wouldn't be surprised if a leading empty line was similarly fragile - it seems rather easy to remove by accident.

This is technically a bug in the formatter, because it is changing the meaning of the script - it used to not have a shebang, and now it does. However, should we also leave a shebang with a leading space untouched? All of these whitespace edge cases feel a tad out of place for a properly formatted shell script.

Perhaps you could consider an alternative like turning the first line into a comment, which could also explain why you don't want the script to have an actual shebang.

**Comment by mvdan** [comment] 2022-10-28 15:03
Thanks for the extra context. We seem to be in agreement that noone would keep a leading empty line in a shell file on purpose, so I'm going to close this issue as "not a supported format" for now. Happy to reconsider that in the future if someone brings forward an argument for its support.

**Closed by mvdan** 2022-10-28 15:03 UTC
