### ISSUE TITLE
syntax: line continuation characters inside a string

### ISSUE THREAD

**Issue by ColemanTom** [mvdan/sh#873] opened 2022-06-06 03:06 UTC
I have just noticed that recently `shfmt` has changed expectations about strings. My guess is it relates to https://github.com/mvdan/sh/pull/837/commits/4556b2f2a22aa51bcfa4e5fde67ed5a89eccab78

I was wondering if this was expected/desired behaviour?

Originally this was fine for `shfmt` (at least with v3.4.2)

```bash
read -r pt ypt mpt <<< \
    "$(date -d "${DATE} -$DIFFERENCE hours" \
        "+%YmdH %Y %m")"
```

Now `shfmt` wants to change it to

```bash
read -r pt ypt mpt <<< "\
$(date -d "${DATE} -$DIFFERENCE hours" \
    "+%YmdH %Y %m")"
```

My personal view is the original was more readable. Otherwise changing it to something like what I have below is possibly clearer still (at least for python devs).

```bash
read -r pt ypt mpt <<< "$(
    "$(date -d "${DATE} -$DIFFERENCE hours" \
        "+%YmdH %Y %m"
)"
```

**Comment by mvdan** [comment] 2022-06-14 10:53
Thanks for raising this; I'm fairly sure this is an unintended regression.

**Comment by mvdan** [comment] 2022-07-03 16:25
Err, I actually wrote a complete fix for this three weeks ago, and I was sure I had already merged it to master. Somehow, I kept it in a local branch and completely forgot about it :) See https://github.com/mvdan/sh/pull/896.

**Closed** 2022-07-04 11:09 UTC
