### ISSUE TITLE
shfmt -kp adds trailing whitespace when formatting a multi-line sub-shell

### ISSUE THREAD

**Issue by alanfalloon** [mvdan/sh#362] opened 2019-03-07 16:13 UTC
I often use sub-shells to limit the scope of shell settings, or to preserve the cwd, and `shfmt` does a nice job of reformatting these with the proper indent -- except that it introduces trailing whitespace after the opening paren. For example:

```bash
( set -e
  cd foo
  git pull )
```

when formatted with `shfmt -i 4 -sr -kp` results in:

```bash
(   
    set -e
    cd foo
    git pull
)
```

with 3 spaces after the opening paren. This doesn't happen if I remove the `-kp` flag, I get the same format but without the trailing whitespace.

**Comment by mvdan** [comment] 2019-03-07 23:10
Thanks for raising this issue! Indeed, trailing spaces should never be printed.

Is there a particular reason why you're using `-kp`, though?

**Comment by mvdan** [comment] 2019-03-18 20:19
Bump @alanfalloon

**Comment by alanfalloon** [comment] 2019-03-19 21:40
I actually removed it from my configuration. I originally added it because it sounded good (alignment seems nice) but I prefer the format without it anyway.

I opened the issue just so you knew about it. I don’t need a fix.

**Comment by mvdan** [comment] 2019-03-26 17:16
Thanks. I agree that `-kp` is generally not a good idea, and sometimes I wonder if I should remove it :)

I'll keep this issue open for now.

**Comment by ralish** [comment] 2020-06-21 10:58
In addition to the issue with multi-line sub-shells there's also some weirdness with multi-line pipes:

Before
```sh
    app_files="$(git ls-files | \
                 grep -E -f "$filters_path/$app_includes_raw" | \
                 grep -E -v -f "$filters_path/$app_excludes_raw")"
```

After
```sh
    app_files="$(git ls-files |
        grep -E -f "$filters_path/$app_includes_raw" |
        grep -E -v -f "$filters_path/$app_excludes_raw")"
```

After with `-kp`
```sh
    app_files="$(git ls-files |
        grep          -E -f "$filters_path/$app_includes_raw" |
        grep          -E -v -f "$filters_path/$app_excludes_raw")"
```

The above snippets were not within a sub-shell.

Regarding usage of `-kp`, I've found it particularly useful to preserve the alignment of comments which are designed to be uncommented as needed. For example:

With `-kp` this snippet is unchanged
```sh
set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
#set -o pipefail        # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)
```

Without `-kp` it ends up being mangled
```sh
set -o errexit  # Exit on most errors (see the manual)
set -o errtrace # Make sure any error trap is inherited
set -o nounset  # Disallow expansion of unset variables
#set -o pipefail        # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)
```

**Comment by mvdan** [comment] 2020-06-21 15:29
@ralish your first snippet seems to be working as intended - `-kp` tries to keep the column position of the original tokens, and since the previous words are getting indented further to the left, the space between the words increases. Note that the column position of `-E` does not change, which is the point of `-kp`.

In general, you should rely on `-kp` to keep your positions stable, not to format everything in a smart way right from the start. With a codebase that has never used `shfmt` before, I expect you'll have to run `shfmt -kp` and do manual tweaks a couple of times before you reach a stable and comfortable format.

As for the "commented comments", that's working as intended, I'm afraid. The parser does not try to parse anything within comments, so it completely ignores those "nested comments". As such, the comments in previous lines are aligned vertically as usual. It's only with `-kp` that such alignment and padding is left completely to the user.

**Comment by ralish** [comment] 2020-06-21 23:29
@mvdan Thanks for the reply. Regarding the "commented comments", agree it's working as intended. I was only providing that as an example where `-kp` is useful in response to your earlier question. Sorry, I should have been clearer.

As for the indent of `-E`, that makes sense, so I guess it's just the original issue re: the trailing spaces.

**Comment by mvdan** [comment] 2020-06-22 08:18
It is true that the naming of `-kp` is a bit confusing, because the way the feature works, we keep column position instead of the space/padding relative to previous tokens. But it's a bit late to change the flag now :)

**Comment by mvdan** [comment] 2021-01-25 13:01
After much thought over a number of years, I'm considering removing this feature in the next major release. See https://github.com/mvdan/sh/issues/658, and please try to keep an open mind when considering the benefits and drawbacks of the flag. Thanks!

**Comment by soulshake** [comment] 2021-05-31 08:30
Commenting here to add the keyword **subshell** to this issue for findability, and pasting my repro here instead of the issue I was about to create :)

```
$ cat --show-ends hello.sh
#!/usr/bin/env bash$
($
    echo "hello world"$
)$

$ docker run --user 1000 --rm -ti -v $PWD:/mnt -w /mnt mvdan/shfmt:v3.2.4 -w -kp hello.sh

$ cat --show-ends hello.sh
#!/usr/bin/env bash$
(   $
	echo  "hello world"$
)$
```

**Comment by mvdan** [comment] 2021-05-31 09:02
Good to hear that you ended up not needing `-kp` :)

**Comment by mvdan** [comment] 2022-10-23 13:37
KeepPadding will definitely be removed in the future v4; see https://github.com/mvdan/sh/issues/658. Closing all existing bug reports as I won't focus more effort on attempting to fix the feature. I'd definitely recommend not to use the option anymore :)

**Closed by mvdan** 2022-10-23 13:37 UTC
