### ISSUE TITLE
dash in variables names

### ISSUE THREAD

**Issue by agrakhov** [mvdan/sh#392] opened 2019-06-19 17:08 UTC
Having problems with following on VS code (author pointed to this repo). 
This:
```bash
declare -A test=(
[test-variable-here]=test-value-here
)
```
transformed to this:

```bash
declare -A test=(
[test - variable - here]=test-value-here
)
```

**Comment by mvdan** [comment] 2019-06-19 18:08
Sorry, but this is by design. See the first item under https://github.com/mvdan/sh#caveats.

I'm open to suggestions, but there isn't much that the static parser can do to distinguish associative arrays (string keys) from indexed arrays (integer keys).

**Comment by mvdan** [comment] 2019-06-24 17:27
It doesn't look like you have any suggestion in particular here, so I'm going to close the issue for now.

**Closed by mvdan** 2019-06-24 17:27 UTC

**Comment by texastoland** [comment] 2020-06-05 06:55
I just got bit my this with paths as keys. Am I wrong that you can'd do mouth outside `((...))`?

**Comment by mvdan** [comment] 2020-06-05 08:10
@texastoland I think you've got it backwards :) We don't know if "index expressions" like `foo[bar]` are integer-like (indexed arrays, or vectors), or string-like (associative arrays, or maps).

So we default to assuming indexed arrays, so we evaluate `foo[1+2]` like `foo[3]`. If you really want `1+2` as a string, you have to explicitly put it between quotes: `foo["1+2"]`.

This is what the caveat section tries to explain: https://github.com/mvdan/sh#caveats

If you think that could be clearer, patches or suggestions are welcome. Ideas to improve the situation are welcome too, just remember that the parser has to be static. It can't interpret the code in any way, such as "was this array declared as indexed or associative?".

**Comment by texastoland** [comment] 2020-06-05 08:17
I see what you mean. I've never used operators in an index expression. I'd argue it's safer (maybe even nicer) to not break math-like dictionary keys than to nicely format math in an index expression. I think they're equally edge-case.

**Comment by mvdan** [comment] 2020-06-05 08:20
:shrug: either option as a default makes sense for some reasons, but not others. The main reason I chose "integer" as the default instead of "string" is because it's also the default when declaring arrays, and it's also what POSIX supports. Associative arrays are a Bash feature, and you have to opt into that mode when declaring an array. So it makes sense to me that you should also "opt in" via syntax hints here, since the syntax is ambiguous for the parser.

**Comment by texastoland** [comment] 2020-06-05 08:23
I assumed that, but one breaks code while the other doesn't. Here's my particular use case:

```bash
typeset -A external_plugins=(
  [zsh-users/zsh-completions]=src
  [zsh-users/zsh-autosuggestions]=true
  [zsh-users/zsh-syntax-highlighting]=true
  [zsh-users/zsh-history-substring-search]=true
)
```

Just weighing in.

**Comment by mvdan** [comment] 2020-06-08 13:11
You'd be breaking valid code either way. What if you meant those as arithmetic operations, and the parser assumes they are just entire strings? Remember that the parser in the syntax package is used for different purposes, not just formatting. For example, the interp package interprets programs.

I can see your point that always parsing index expressions as just strings might be more conservative in some scenarios, but it's only because it "gives up" and never does proper arithmetic expression parsing. Generally, we want the parser to do as much static parsing as possible, without needing a second parse pass to properly see what the program is meant to do.

**Comment by texastoland** [comment] 2020-06-09 09:58
I didn't realize that. In practice, URLs might be the only use case for math-like keys anyway. Thanks for explaining!
